version: "3.3"
services:
  backend:
    container_name: backend
    build: "backend"
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/usr/src/app/
    links:
      - mongo
    depends_on:
      - mongo
    command: "node /usr/src/app/bin/www"

  frontend:
    container_name: frontend
    build: "frontend"
    ports:
      - "8081:4200"
    volumes:
      - ./frontend:/usr/src/app/
    links:
      - backend
    depends_on:
      - backend
    command: "ng serve --host 0.0.0.0 --port 4200 --proxy-config src/proxy.conf.json"

  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: upteam
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js

